### ISSUE TITLE
Cannot access guacamole with error protocol violation

### ISSUE THREAD

**Issue by ispmarin** [linuxserver/docker-guacd#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

After including the guacd image on my docker-compose file, the service starts correctly, but cannot be accessed. I get the following errors:
```
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
```
------------------------------

## Expected Behavior
It should show the desktop

## Current Behavior
Not found in browser, no access to service

## Steps to Reproduce
1. Deploy Guacamole on docker-compose
2. Start service with docker-compose up
3. Access the url with the right port
4. failure to access

## Environment
**OS:** Debian 10
**CPU architecture:** x86_64
**How docker service was installed:**
Docker official repos

## Command used to create docker container (run/create/compose/screenshot)
```
---
version: "3"
services:

  guacamole:
    container_name: guacamole
    image: ghcr.io/linuxserver/guacd
    container_name: guacd
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=America/${TZ}"
      - UMASK_SET=<022> 
    ports:
      - 9022:4822
    restart: unless-stopped
```
## Docker logs
```
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?
guacd           | guacd[246]: ERROR:    Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?

```

**Comment by technorabilia** [comment]
Same error.

guacd[244]: ERROR:	Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?

**Comment by isudoi** [comment]
Same here as well

`guacd[240]: ERROR:	Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?`

I have a very a basic setup 

Synology NAS DSM
Portainer Stack

```
version: "2"
services:
  guacamole:
    image: ghcr.io/linuxserver/guacd
    container_name: guacamole_linuxserver_test
    volumes:
      - /volume1/docker/guacamole/linuxserver-guacd-test:/config
    ports:
      - 8012:4822
```
